//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsOfficeClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsOfficeClient.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მესიჯი წარმატებით გადაეცა SMS ოფისს. ეს ჯერ არ ნიშნავს, რომ მესიჯი მიიღო მობილურმა ტელეფონმა. მიღების შედეგი ნაჩვენები იქნება მიღების უწყისში.
        /// </summary>
        public static string Result01 {
            get {
                return ResourceManager.GetString("Result01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხოვნას აკლია ერთი ან რამოდენიმე სავალდებულო პარამეტრი.
        /// </summary>
        public static string Result100 {
            get {
                return ResourceManager.GetString("Result100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ერთი ან რამოდენიმე პარამეტრის მნიშვნელობა არასწორია.
        /// </summary>
        public static string Result120 {
            get {
                return ResourceManager.GetString("Result120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დეპოზოტი არასაკმარისია.
        /// </summary>
        public static string Result130 {
            get {
                return ResourceManager.GetString("Result130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ender პარამეტრის მნიშვნელობა არასწორია.
        /// </summary>
        public static string Result200 {
            get {
                return ResourceManager.GetString("Result200", resourceCulture);
            }
        }
    }
}
